# Site Settings
title: Projet Michel
description: >
  Il était une fois la 3D ...
baseurl: ""
url: "https://localhost:4000/"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
