# Site Settings
title: Projet Michel
description: >
  Il était une fois la 3D ...
baseurl: "/projetmichel"
url: "https://trakjohnson.github.io"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
