# Site Settings
title: Projet Michel
description: >
  Il était une fois la 3D ...
baseurl: ""
url: "https://localhost:4000/"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
markdown: CommonMark
